# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e72dfd315390daaa12043a5e5a8c5b5554539cefc395d3e2605a78be52c864f03f24a96a876e5e8fe79c7c6081afe21aa84e407f503a28ee6f9681092855dc76

test:
  secret_key_base: 265c25aff59315947ffc5251b19a55a8cf7b2fecc4e492939cf9e08f6e605f44ad5773a35b552bb340d579b6978b4ddc5671d6cd172f1f319466bd2f83540c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
